/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BgPreview: typeof import('./components/BgPreview.vue')['default']
    ColorInput: typeof import('./components/ColorInput.vue')['default']
    ColorPaletteSelector: typeof import('./components/ColorPaletteSelector.vue')['default']
    Controls: typeof import('./components/Controls.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RandomPreview: typeof import('./components/RandomPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateSwitcher: typeof import('./components/TemplateSwitcher.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    Toasts: typeof import('./components/Toasts.vue')['default']
  }
}
